"""Tests for the Zotero MCP Server implementation"""

import logging
import json

import pytest

from zotero_mcp_server.zotero_mcp_server import pyzotero_search_library,get_parent_collections
from zotero_mcp_server.parser import note_title_parser


logging.basicConfig(
    level=logging.INFO,
    datefmt="%Y-%m-%d %H:%M:%S",
    format="%(asctime)s - %(levelname)s - %(message)s"
)
test_logger = logging.getLogger(__name__)


class TestPyzoteroSearch:
    """Collection of tests regarding my pyzotero search wrapper."""

    # Simulates inputs generated by an llm
    @pytest.mark.parametrize("limit, query",[
        (0, ""), # For wrongly set limit by llm
        (1, "Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz"), # For no result case
        (10, "llm"),
        (100, "llm"),
        (10000, "git"),
        (100, ""),
        (100000, "")
    ])
    def test_pyzotero_search_library(self, limit: int, query: str) -> None:
        """Test pyzotero search library function"""
        test_logger.info("Running test with limit: %d and query: %s", limit, query)
        assert isinstance(limit, int)
        assert isinstance(query, str)

        found_items = pyzotero_search_library(limit=limit, query=query)

        assert isinstance(found_items, list)
        if found_items:
            for found_item in found_items:
                assert isinstance(found_item, dict)

    # def test_pyzotero_search_parser(self) -> None:
    #     raise NotImplementedError

    # Similates the collection key of a found item
    @pytest.mark.parametrize("collection_key", ["8NXHKXXC"])
    def test_get_parent_collections(self, collection_key: str) -> None:
        """Test recursively retrieving the names of a collection and its parent collections"""

        test_logger.info("Running test with collection_key: %s", collection_key)

        item_collection_names = get_parent_collections(collection_key)[0]

        test_item_collection_names = ['Collection depth=0: Machine Learning',
                                        'Collection depth=1: Interesting Ideas',
                                        'Collection depth=2: MCP (Model Context Protocol)']
        assert item_collection_names == test_item_collection_names

@pytest.fixture(scope="function", name="static_pyzotero_items_fixture")
def static_pyzotero_items():
    """Fixture to load static pyzotero responses from a JSON file."""
    
    return _read_json("./tests/test_pyzotero_items.json")

@pytest.fixture(scope="function", name="notes_items_fixture")
def notes_items(static_pyzotero_items_fixture):
    """Fixture to extract the note items from the static pyzotero items"""
    return static_pyzotero_items_fixture["notes"]

@pytest.fixture(scope="function", name="notes_html_fixture")
def notes_html(notes_items_fixture):
    """Fixture to extract the notes html from note items."""
    return [note_item["data"]["note"] for note_item in notes_items_fixture]

@pytest.fixture(scope="function", name="notes_titles_fixture")
def notes_titles(notes_items_fixture):
    """Fixture to extract the notes html from note items."""
    return [note_item["data"]["test_note_title"] for note_item in notes_items_fixture]

class TestParsers:
    """Test for different pyzotero item type parsers"""

    def test_note_title_parser(self, notes_html_fixture, notes_titles_fixture):
        """Test note title parser extracts correct note"""

        parsed_notes_titles = [note_title_parser(note_html) for note_html in notes_html_fixture]
        assert parsed_notes_titles == notes_titles_fixture


def _read_json(filename: str) -> dict:
    """Reads data from a JSON file and returns it as a Python dictionary.

    Args:cl
        filename (str): The name of the JSON file to read.

    Returns:
        dict: A Python dictionary representing the data from the JSON file.
              Returns an empty dictionary if the file is not found or an error occurs.
    """
    try:
        with open(filename, "r", encoding="utf-8") as json_file:
            data = json.load(json_file)
        return data
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return {}
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{filename}'. \
              The file might be corrupted or not valid JSON.")
        return {}
    except IOError as e:
        print(f"Error reading file '{filename}': {e}")
        return {}

# {'key': 'XGQHZEGZ',
# 'version': 0,
# 'library': {'type': 'user',
# 'id': 11338754,
# 'name': 'My Library',
# 'links': {'self': {'href': 'http://localhost:23119/api/users/11338754',
#     'type': 'application/json'},
# 'alternate': {'href': 'https://www.zotero.org/users/11338754',
#     'type': 'text/html'}}},
# 'links': {'self': {'href': 'http://localhost:23119/api/users/11338754/items/XGQHZEGZ',
# 'type': 'application/json'},
# 'alternate': {'href': 'https://www.zotero.org/users/11338754/items/XGQHZEGZ',
# 'type': 'text/html'}},
# 'meta': {'numChildren': 0},
# 'data': {'key': 'XGQHZEGZ',
# 'version': 0,
# 'itemType': 'note',
# 'note': '<div data-schema-version="9"><h1>02 Quickstart: For Server Developers</h1>\n<ul>\n<li>\nBuild a simple MCP weather server with <code>get-alerts</code> and <code>get-forecast</code> tools.\n</li>\n<li>\nConnect the server to Claude for Desktop (an MCP host).\n</li>\n<li>\nMCP servers can provide Resources, Tools, and Prompts. This tutorial focuses on Tools.\n</li>\n<li>\nRequires Python 3.10+, MCP SDK 1.2.0+, and familiarity with Python and LLMs like Claude.\n</li>\n<li>\nUse <code>uv</code> to set up the Python environment and install dependencies.\n</li>\n<li>\nThe server interacts with the National Weather Service (NWS) API.\n</li>\n<li>\n<code>FastMCP</code> framework simplifies building MCP servers in Python.\n</li>\n<li>\nTool definitions are automatically generated using type hints and docstrings.\n</li>\n<li>\nClaude for Desktop needs to be configured with the server details to use the tools.\n</li>\n<li>\nUsers can interact with the server\'s tools through commands in Claude for Desktop.\n</li>\n</ul>\n<h1>Quickstart for Server Developers</h1>\n<h2>Introduction</h2>\n<p>This tutorial guides server developers on how to build their own server to be used with MCP (Machine Communication Protocol) clients like Claude for Desktop. It demonstrates the process by building a simple MCP weather server that can fetch weather forecasts and severe weather alerts.</p>\n<h2>What We\'ll Be Building</h2>\n<p>The goal is to create a server that exposes two main tools: <code>get-alerts</code> and <code>get-forecast</code>. This server will then be connected to an MCP host, in this case, Claude for Desktop, allowing the LLM to access real-time weather information. While Claude for Desktop is used for simplicity, servers built using this protocol can connect to various other clients.</p>\n<h2>Core MCP Concepts</h2>\n<p>MCP servers offer three primary capabilities:</p>\n<ul>\n<li>\n<strong>Resources:</strong> These are file-like data that clients can read, such as API responses or file contents.\n</li>\n<li>\n<strong>Tools:</strong> These are functions that the LLM can call (with user approval) to perform specific actions. This tutorial focuses mainly on building tools.\n</li>\n<li>\n<strong>Prompts:</strong> These are pre-written templates designed to help users accomplish specific tasks more easily.\n</li>\n</ul>\n<h2>Prerequisites</h2>\n<p>Before starting, ensure you have the following:</p>\n<ul>\n<li>\nFamiliarity with Python.\n</li>\n<li>\nUnderstanding of LLMs like Claude.\n</li>\n<li>\n<p>System Requirements:</p>\n<ul>\n<li>\nPython 3.10 or higher installed.\n</li>\n<li>\nPython MCP SDK version 1.2.0 or higher.\n</li>\n</ul>\n</li>\n</ul>\n<h2>Setting Up Your Environment</h2>\n<p>The first step is to set up your development environment. This involves installing <code>uv</code>, a fast Python package installer and resolver, and creating a new Python project.</p>\n<ol>\n<li>\n<p><strong>Install </strong><code>uv</code>:</p>\n<ul>\n<li>\n<p><strong>MacOS/Linux:</strong></p>\n<pre>curl -LsSf https://astral.sh/uv/install.sh | sh</pre>\n</li>\n<li>\n<strong>Windows:</strong> Follow the instructions from the provided link.\n</li>\n<li>\nRestart your terminal after installation.\n</li>\n</ul>\n</li>\n<li>\n<p><strong>Create and Set Up Project:</strong></p>\n<ul>\n<li>\n<p>Create a new directory for your project:</p>\n<pre>uv init weather\ncd weather</pre>\n</li>\n<li>\n<p>Create and activate a virtual environment:</p>\n<pre>uv venv\nsource .venv/bin/activate</pre>\n</li>\n<li>\n<p>Install necessary dependencies:</p>\n<pre>uv add "mcp[cli]" httpx</pre>\n</li>\n<li>\n<p>Create the main server file:</p>\n<pre>touch weather.py</pre>\n</li>\n</ul>\n</li>\n</ol>\n<h2>Building Your Server</h2>\n<h3>Importing Packages and Setting Up the Instance</h3>\n<p>In your <code>weather.py</code> file, start by importing the required packages and initializing the <code>FastMCP</code> server.</p>\n<pre>from typing import Any\nimport httpx\nfrom mcp.server.fastmcp import FastMCP\n\n# Initialize FastMCP server\nmcp = FastMCP("weather")\n\n# Constants\nNWS_API_BASE = "https://api.weather.gov"\nUSER_AGENT = "weather-app/1.0"</pre>\n<p>The <code>FastMCP</code> class simplifies tool creation by using Python type hints and docstrings to automatically generate tool definitions.</p>\n<h3>Helper Functions</h3>\n<p>Next, define helper functions to interact with the National Weather Service (NWS) API and format the responses.</p>\n<pre>async def make_nws_request(url: str) -&gt; dict[str, Any] | None:\n &nbsp; &nbsp;"""Make a request to the NWS API with proper error handling."""\n &nbsp; &nbsp;headers = {\n &nbsp; &nbsp; &nbsp; &nbsp;"User-Agent": USER_AGENT,\n &nbsp; &nbsp; &nbsp; &nbsp;"Accept": "application/geo+json"\n &nbsp; &nbsp;}\n &nbsp; &nbsp;async with httpx.AsyncClient() as client:\n &nbsp; &nbsp; &nbsp; &nbsp;try:\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;response = await client.get(url, headers=headers, timeout=30.0)\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;response.raise_for_status()\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;return response.json()\n &nbsp; &nbsp; &nbsp; &nbsp;except Exception:\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;return None\n\ndef format_alert(feature: dict) -&gt; str:\n &nbsp; &nbsp;"""Format an alert feature into a readable string."""\n &nbsp; &nbsp;props = feature["properties"]\n &nbsp; &nbsp;return f"""Event: {props.get(\'event\', \'Unknown\')}\nArea: {props.get(\'areaDesc\', \'Unknown\')}\nSeverity: {props.get(\'severity\', \'Unknown\')}\nDescription: {props.get(\'description\', \'No description available\')}\nInstructions: {props.get(\'instruction\', \'No specific instructions provided\')}"""</pre>\n<h3>Implementing Tool Execution</h3>\n<p>Implement the logic for the <code>get-alerts</code> and <code>get-forecast</code> tools using the <code>@mcp.tool()</code> decorator.</p>\n<pre>@mcp.tool()\nasync def get_alerts(state: str) -&gt; str:\n &nbsp; &nbsp;"""Get weather alerts for a US state.\n &nbsp; &nbsp;Args:\n &nbsp; &nbsp; &nbsp; &nbsp;state: Two-letter US state code (e.g. CA, NY)\n &nbsp; &nbsp;"""\n &nbsp; &nbsp;url = f"{NWS_API_BASE}/alerts/active/area/{state}"\n &nbsp; &nbsp;data = await make_nws_request(url)\n &nbsp; &nbsp;if not data or "features" not in data:\n &nbsp; &nbsp; &nbsp; &nbsp;return "Unable to fetch alerts or no alerts found."\n &nbsp; &nbsp;if not data["features"]:\n &nbsp; &nbsp; &nbsp; &nbsp;return "No active alerts for this state."\n &nbsp; &nbsp;alerts = [format_alert(feature) for feature in data["features"]]\n &nbsp; &nbsp;return "\\n---\\n".join(alerts)\n\n@mcp.tool()\nasync def get_forecast(latitude: float, longitude: float) -&gt; str:\n &nbsp; &nbsp;"""Get weather forecast for a location.\n &nbsp; &nbsp;Args:\n &nbsp; &nbsp; &nbsp; &nbsp;latitude: Latitude of the location\n &nbsp; &nbsp; &nbsp; &nbsp;longitude: Longitude of the location\n &nbsp; &nbsp;"""\n &nbsp; &nbsp;# First get the forecast grid endpoint\n &nbsp; &nbsp;points_url = f"{NWS_API_BASE}/points/{latitude},{longitude}"\n &nbsp; &nbsp;points_data = await make_nws_request(points_url)\n &nbsp; &nbsp;if not points_data:\n &nbsp; &nbsp; &nbsp; &nbsp;return "Unable to fetch forecast data for this location."\n &nbsp; &nbsp;# Get the forecast URL from the points response\n &nbsp; &nbsp;forecast_url = points_data["properties"]["forecast"]\n &nbsp; &nbsp;forecast_data = await make_nws_request(forecast_url)\n &nbsp; &nbsp;if not forecast_data:\n &nbsp; &nbsp; &nbsp; &nbsp;return "Unable to fetch detailed forecast."\n &nbsp; &nbsp;# Format the periods into a readable forecast\n &nbsp; &nbsp;periods = forecast_data["properties"]["periods"]\n &nbsp; &nbsp;forecasts = []\n &nbsp; &nbsp;for period in periods[:5]: &nbsp;# Only show next 5 periods\n &nbsp; &nbsp; &nbsp; &nbsp;forecast = f"""{period[\'name\']}:\nTemperature: {period[\'temperature\']}°{period[\'temperatureUnit\']}\nWind: {period[\'windSpeed\']} {period[\'windDirection\']}\nForecast: {period[\'detailedForecast\']}"""\n &nbsp; &nbsp; &nbsp; &nbsp;forecasts.append(forecast)\n &nbsp; &nbsp;return "\\n---\\n".join(forecasts)</pre>\n<h2>Running the Server</h2>\n<p>Finally, add the code to initialize and run the server when the script is executed directly.</p>\n<pre>if __name__ == "__main__":\n &nbsp; &nbsp;# Initialize and run the server\n &nbsp; &nbsp;mcp.run(transport=\'stdio\')</pre>\n<p>You can run your server using the command <code>uv run weather.py</code>.</p>\n<h2>Testing Your Server with Claude for Desktop</h2>\n<p>To test your server, you need to configure Claude for Desktop to recognize and connect to it.</p>\n<ol>\n<li>\n<strong>Install or Update Claude for Desktop:</strong> Ensure you have Claude for Desktop installed and updated to the latest version.\n</li>\n<li>\n<p><strong>Configure Claude for Desktop:</strong></p>\n<ul>\n<li>\nOpen the Claude for Desktop App configuration file located at <code>~/Library/Application Support/Claude/claude_desktop_config.json</code> (MacOS/Linux) or the equivalent location on Windows. Create the file if it doesn\'t exist.\n</li>\n<li>\n<p>Add your server configuration under the <code>mcpServers</code> key. For the weather server, it might look like this:</p>\n<pre>{\n &nbsp; &nbsp;"mcpServers": {\n &nbsp; &nbsp; &nbsp; &nbsp;"weather": {\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"command": "uv",\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"args": [\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"--directory",\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"/ABSOLUTE/PATH/TO/PARENT/FOLDER/weather",\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"run",\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;"weather.py"\n &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;]\n &nbsp; &nbsp; &nbsp; &nbsp;}\n &nbsp; &nbsp;}\n}</pre>\n<ul>\n<li>\nReplace <code>/ABSOLUTE/PATH/TO/PARENT/FOLDER/weather</code> with the actual absolute path to the parent directory of your <code>weather</code> project.\n</li>\n<li>\nYou might need to provide the full path to the <code>uv</code> executable in the <code>command</code> field. Use <code>which uv</code> (MacOS/Linux) or <code>where uv</code> (Windows) to find it.\n</li>\n</ul>\n</li>\n</ul>\n</li>\n<li>\n<strong>Restart Claude for Desktop:</strong> Save the configuration file and restart Claude for Desktop.\n</li>\n<li>\n<p><strong>Test with Commands:</strong></p>\n<ul>\n<li>\nLook for the hammer icon in Claude for Desktop, which indicates that MCP servers are configured.\n</li>\n<li>\nClicking the hammer icon should display the <code>get-alerts</code> and <code>get-forecast</code> tools.\n</li>\n<li>\n<p>You can now test the server by asking questions like:</p>\n<ul>\n<li>\n<code>What’s the weather in Sacramento?</code>\n</li>\n<li>\n<code>What are the active weather alerts in Texas?</code>\n</li>\n</ul>\n</li>\n</ul>\n<p>Note that the weather service used is the US National Weather Service, so queries should be for US locations.</p>\n</li>\n</ol>\n<h2>What’s Happening Under the Hood</h2>\n<p>When you ask a question in Claude for Desktop that requires information from your weather server:</p>\n<ol>\n<li>\nThe client (Claude for Desktop) sends your question to Claude.\n</li>\n<li>\nClaude analyzes the available tools and determines if any of them can help answer the question.\n</li>\n<li>\nIf a tool is deemed necessary, the client executes the chosen tool through your MCP server.\n</li>\n<li>\nYour server processes the request (e.g., fetches data from the NWS API) and sends the results back to Claude.\n</li>\n<li>\nClaude uses the results to formulate a natural language response, which is then displayed to you.\n</li>\n</ol>\n</div>',
# 'tags': [],
# 'collections': ['8NXHKXXC'],
# 'relations': {},
# 'dateAdded': '2025-04-08T09:35:03Z',
# 'dateModified': '2025-04-08T09:37:32Z'}}







