name: Python CI

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

jobs:
    python_ci:
        runs-on: ubuntu-latest
        env:
            LIBRARY_ID: ${{ secrets.LIBRARY_ID }}
            LIBRARY_TYPE: ${{ secrets.LIBRARY_TYPE }}

        steps:
            
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Install the project
              run: uv sync --all-extras --dev
            
            - name: Install zotero_mcp_server as package
              run: uv pip install .
            
            - name: Analysing the code with pylint
              run: uv run pylint --fail-under=9.0 --max-line-length=120 $(git ls-files '*.py')

            - name: Run tests
              run: uv run pytest tests --cov
